name: 'Authenticate to Polar'
description: 'Polar Polarify'

branding:
  icon: lock
  color: blue

inputs:
  scope:
    description: "List of scopes to request for the Polar access token."
    default: "openid"
    required: true

outputs:
  token:
    description: "A Polar access token."
    value: ${{ steps.mint-token.outputs.token }}

runs:
  using: 'composite'
  steps:
    - name: Mint a Polar access token
      id: mint-token
      shell: bash
      run: |
        # Retrieve the ambient OIDC token
        resp=$(curl --fail-with-body -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=polar")
        oidc_token=$(jq -r '.value' <<< "${resp}")
        # Mint the token
        resp=$(curl --fail-with-body -XPOST -d "grant_type=github_oidc_id_token&id_token=${oidc_token}&scope=$SCOPE" https://fvoron-polar.ngrok.dev/api/v1/oauth2/token)
        access_token=$(jq -r '.access_token' <<< "${resp}")
        # Output it
        echo "token=$(echo $access_token)" >> $GITHUB_OUTPUT
      env:
        SCOPE: ${{ inputs.scope }}
