name: Client
 
on:
  push:
    branches: ["main"]
#   pull_request:
    # types: [opened, synchronize]
 
jobs:
  build:
      name: "Self-Polarify"
      timeout-minutes: 15
      runs-on: ubuntu-22.04
 
      steps:
        - name: Check out code
          uses: actions/checkout@v3

        - name: Polarify
          uses: polarsource/actions/polarify@main
          with:
            path: "**/demo.md"

        - uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: Update polar comments